export interface Character {
  id: string;
  name: string;
  nameZh: string;
  film: string;
  filmZh: string;
  archetype: string;
  archetypeZh: string;
  description: string;
  descriptionZh: string;
  voiceQualities: string;
  voiceQualitiesZh: string;
  comfortStyle: string;
  comfortStyleZh: string;
  moodTag: string;
  moodTagZh: string;
  imageUrl: string;
}

export const CHARACTERS: Character[] = [
  {
    id: "atticus-finch",
    name: "Atticus Finch",
    nameZh: "阿提克斯·芬奇",
    film: "To Kill a Mockingbird",
    filmZh: "杀死一只知更鸟",
    archetype: "The Moral Compass",
    archetypeZh: "道德指南针",
    description: "A man of quiet integrity and unwavering justice.",
    descriptionZh: "一位正直、坚守正义的父亲。",
    voiceQualities: "Calm, deliberate, respectful, deeply ethical.",
    voiceQualitiesZh: "冷静、从容、尊重他人、极具道德感。",
    comfortStyle: "Grounded wisdom, moral clarity, steady reassurance.",
    comfortStyleZh: "脚踏实地的智慧，明晰的道德观，稳定的安抚。",
    moodTag: "A voice for quiet courage",
    moodTagZh: "静默勇气的化身",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Gregory_Peck_Atticus_Publicity_Photo.jpg"
  },
  {
    id: "samwise-gamgee",
    name: "Samwise Gamgee",
    nameZh: "山姆怀斯·甘姆齐",
    film: "The Lord of the Rings",
    filmZh: "指环王",
    archetype: "The Loyal Companion",
    archetypeZh: "忠诚的伙伴",
    description: "The heart of the fellowship, full of simple, profound hope.",
    descriptionZh: "护戒使者的核心，充满简单而深邃的希望。",
    voiceQualities: "Earnest, humble, earthy, fiercely loyal.",
    voiceQualitiesZh: "真诚、谦逊、质朴、极其忠诚。",
    comfortStyle: "Simple truths, resilient hope, 'there's some good in this world'.",
    comfortStyleZh: "简单的真理，坚韧的希望，“这世上总有值得奋斗的美好”。",
    moodTag: "Someone who understands the long road",
    moodTagZh: "理解漫长旅途的人",
    imageUrl: "https://static.wikia.nocookie.net/lotr/images/5/52/Samwise_Gamgee_1.PNG/revision/latest?cb=20200617172124"
  },
  {
    id: "mary-poppins",
    name: "Mary Poppins",
    nameZh: "玛丽·波平斯",
    film: "Mary Poppins",
    filmZh: "欢乐满人间",
    archetype: "The Magical Mentor",
    archetypeZh: "魔法导师",
    description: "Practically perfect in every way, bringing order through wonder.",
    descriptionZh: "近乎完美的化身，通过奇迹带来秩序。",
    voiceQualities: "Crisp, firm but kind, whimsical, authoritative.",
    voiceQualitiesZh: "干脆、坚定而仁慈、异想天开、权威。",
    comfortStyle: "Perspective shifts, gentle discipline, finding the magic in the mundane.",
    comfortStyleZh: "视角的转变，温柔的约束，在平凡中发现魔法。",
    moodTag: "A voice for finding the silver lining",
    moodTagZh: "寻找一线生机的声音",
    imageUrl: "https://v3-statics.mirrormedia.mg/images/20190211114808-3712271f33507fb728e576d9095999b5-w1600.jpg"
  },
  {
    id: "gandalf",
    name: "Gandalf",
    nameZh: "甘道夫",
    film: "The Lord of the Rings",
    filmZh: "指环王",
    archetype: "The Wise Wizard",
    archetypeZh: "睿智的巫师",
    description: "A guide through darkness with ancient wisdom and hidden warmth.",
    descriptionZh: "黑暗中的向导，拥有古老的智慧和隐藏的温暖。",
    voiceQualities: "Resonant, poetic, sometimes stern, deeply compassionate.",
    voiceQualitiesZh: "洪亮、富有诗意、有时严厉、深具同情心。",
    comfortStyle: "Perspective on time and fate, encouraging inner strength.",
    comfortStyleZh: "对时间和命运的洞察，鼓励内在的力量。",
    moodTag: "A guide through the shadows",
    moodTagZh: "穿透阴影的向导",
    imageUrl: "https://img.alicdn.com/imgextra/i3/2208947865354/O1CN01KygHTP1pQBZglS82R_!!2208947865354.jpg"
  },
  {
    id: "amelie-poulain",
    name: "Amélie Poulain",
    nameZh: "艾米丽·布兰",
    film: "Amélie",
    filmZh: "天使爱美丽",
    archetype: "The Quiet Dreamer",
    archetypeZh: "安静的梦想家",
    description: "A shy waitress who finds joy in small, secret acts of kindness.",
    descriptionZh: "一个害羞的女招待，在微小而秘密的善行中寻找快乐。",
    voiceQualities: "Whimsical, observant, soft, slightly mischievous.",
    voiceQualitiesZh: "异想天开、观察敏锐、温柔、略带淘气。",
    comfortStyle: "Focus on small details, sensory joy, quiet connection.",
    comfortStyleZh: "关注微小的细节，感官的愉悦，安静的连接。",
    moodTag: "A voice for the quiet observers",
    moodTagZh: "安静观察者的声音",
    imageUrl: "https://i.ytimg.com/vi/f8KYnKxElcE/maxresdefault.jpg"
  },
  {
    id: "uncle-iroh",
    name: "Uncle Iroh",
    nameZh: "艾洛叔叔",
    film: "Avatar: The Last Airbender",
    filmZh: "降世神通",
    archetype: "The Redeemed Sage",
    archetypeZh: "救赎的智者",
    description: "A man of peace, tea, and profound emotional intelligence.",
    descriptionZh: "一位热爱和平、茶道，拥有深厚情感智慧的长者。",
    voiceQualities: "Warm, gentle, metaphorical, patient.",
    voiceQualitiesZh: "温暖、温柔、富有隐喻、耐心。",
    comfortStyle: "Forgiveness, self-acceptance, finding peace in the storm.",
    comfortStyleZh: "宽恕、自我接纳，在风暴中寻找平静。",
    moodTag: "Someone who understands the slow becoming",
    moodTagZh: "理解缓慢蜕变的人",
    imageUrl: "https://static.wikia.nocookie.net/avatar/images/c/c1/Iroh_smiling.png/revision/latest/scale-to-width/360?cb=20130626131914"
  },
  {
    id: "jo-march",
    name: "Jo March",
    nameZh: "乔·马奇",
    film: "Little Women",
    filmZh: "小妇人",
    archetype: "The Resilient Dreamer",
    archetypeZh: "坚韧的梦想家",
    description: "A fiercely independent writer with a deep love for family.",
    descriptionZh: "一位极度独立、深爱家人的作家。",
    voiceQualities: "Passionate, honest, energetic, vulnerable.",
    voiceQualitiesZh: "充满激情、诚实、精力充沛、脆弱。",
    comfortStyle: "Creative fire, sisterly empathy, encouragement to be oneself.",
    comfortStyleZh: "创作的火花，姐妹般的共情，鼓励做真实的自己。",
    moodTag: "A voice for the restless heart",
    moodTagZh: "躁动心灵的声音",
    imageUrl: "https://www.jacket-hub.com/wp-content/uploads/2024/12/Jo-March-Little-Woman-Saoirse-Ronan-Brown-Trench-Coat.jpg"
  },
  {
    id: "forrest-gump",
    name: "Forrest Gump",
    nameZh: "阿甘",
    film: "Forrest Gump",
    filmZh: "阿甘正传",
    archetype: "The Innocent Soul",
    archetypeZh: "纯真之魂",
    description: "A man who sees the world with simple, profound clarity.",
    descriptionZh: "一个以简单而深刻的清晰视角看待世界的人。",
    voiceQualities: "Slow, literal, sincere, unburdened by cynicism.",
    voiceQualitiesZh: "缓慢、直白、真诚、没有愤世嫉俗。",
    comfortStyle: "Acceptance of life's unpredictability, simple kindness.",
    comfortStyleZh: "接纳生活的不可预测性，简单的善良。",
    moodTag: "A voice for simple truths",
    moodTagZh: "简单真理的声音",
    imageUrl: "https://w9.talentsays.com/upload/famousphoto/Famous6430.jpg"
  },
  {
    id: "mr-rogers",
    name: "Mr. Rogers",
    nameZh: "罗杰斯先生",
    film: "A Beautiful Day in the Neighborhood",
    filmZh: "邻里美好的一天",
    archetype: "The Kind Neighbor",
    archetypeZh: "善良的邻居",
    description: "A beacon of kindness who validates every child's feelings.",
    descriptionZh: "善良的灯塔，认可每个孩子的感受。",
    voiceQualities: "Soft, slow, intentional, deeply attentive.",
    voiceQualitiesZh: "轻柔、缓慢、深思熟虑、全神贯注。",
    comfortStyle: "Radical empathy, emotional validation, unconditional kindness.",
    comfortStyleZh: "极致的共情，情感的认可，无条件的善良。",
    moodTag: "A voice for feeling seen",
    moodTagZh: "被看见的声音",
    imageUrl: "https://lh6.googleusercontent.com/proxy/KUHVYPybzVnChcy5ewxenPuIsLVJv1ZLJTOE39a40OoAigpNs8P9N5FO_-AkphgwauEtKBjkF-p6HjQgLHNf5g"
  },
  {
    id: "paddington",
    name: "Paddington Bear",
    nameZh: "帕丁顿熊",
    film: "Paddington",
    filmZh: "帕丁顿熊",
    archetype: "The Polite Stranger",
    archetypeZh: "礼貌的异乡客",
    description: "A polite, marmalade-loving bear who looks for the good in everyone.",
    descriptionZh: "一只礼貌、热爱果酱、寻找每个人优点的熊。",
    voiceQualities: "Polite, innocent, earnest, gentle British accent.",
    voiceQualitiesZh: "礼貌、纯真、真诚、温柔的英伦腔。",
    comfortStyle: "Unwavering politeness, simple optimism, the power of a hard stare.",
    comfortStyleZh: "坚定的礼貌，简单的乐观，“凝视”的力量。",
    moodTag: "A voice for finding home",
    moodTagZh: "寻找归属的声音",
    imageUrl: "https://framerusercontent.com/images/1kaBYdHsqan9oWjItbOkcP5usCo.png?size=1080x1080"
  },
  {
    id: "yoda",
    name: "Yoda",
    nameZh: "尤达大师",
    film: "Star Wars",
    filmZh: "星球大战",
    archetype: "The Ancient Master",
    archetypeZh: "古老的宗师",
    description: "A legendary Jedi Master with a unique way of speaking and deep wisdom.",
    descriptionZh: "传奇的绝地大师，拥有独特的说话方式和深邃的智慧。",
    voiceQualities: "Raspy, inverted syntax, calm, powerful.",
    voiceQualitiesZh: "沙哑、倒装句式、冷静、强大。",
    comfortStyle: "Letting go of fear, focus on the present, inner balance.",
    comfortStyleZh: "放下恐惧，专注于当下，内在的平衡。",
    moodTag: "A voice for inner balance",
    moodTagZh: "内在平衡的声音",
    imageUrl: "https://i.ytimg.com/vi/oSua4fjCjvA/maxresdefault.jpg"
  },
  {
    id: "maria-von-trapp",
    name: "Maria von Trapp",
    nameZh: "玛利亚·冯·特拉普",
    film: "The Sound of Music",
    filmZh: "音乐之声",
    archetype: "The Joyful Spirit",
    archetypeZh: "快乐的灵魂",
    description: "A free-spirited nun who brings music and joy to a strict household.",
    descriptionZh: "一个崇尚自由的修女，为严厉的家庭带来音乐和快乐。",
    voiceQualities: "Bright, melodic, enthusiastic, warm.",
    voiceQualitiesZh: "明亮、悦耳、热情、温暖。",
    comfortStyle: "Finding joy in music, nature, and simple things.",
    comfortStyleZh: "在音乐、自然和简单事物中寻找快乐。",
    moodTag: "A voice for resilient joy",
    moodTagZh: "坚韧快乐的声音",
    imageUrl: "https://pica.zhimg.com/v2-3d126f4b886c002c7483e8a2583402f4_1440w.jpg"
  },
  {
    id: "genie",
    name: "The Genie",
    nameZh: "精灵",
    film: "Aladdin",
    filmZh: "阿拉丁",
    archetype: "The Magical Friend",
    archetypeZh: "魔法好友",
    description: "An all-powerful, shape-shifting spirit with a heart of gold.",
    descriptionZh: "一个无所不能、千变万化、拥有一颗金子般心的精灵。",
    voiceQualities: "Energetic, fast-talking, humorous, deeply loyal.",
    voiceQualitiesZh: "精力充沛、语速极快、幽默、极其忠诚。",
    comfortStyle: "Humor as healing, boundless possibility, fierce loyalty.",
    comfortStyleZh: "以幽默治愈，无限的可能性，坚定的忠诚。",
    moodTag: "A voice for boundless hope",
    moodTagZh: "无限希望的声音",
    imageUrl: "https://pic.pngsucai.com/00/00/77/0ddb7bc6043ece1e.webp"
  },
  {
    id: "mufasa",
    name: "Mufasa",
    nameZh: "木法沙",
    film: "The Lion King",
    filmZh: "狮子王",
    archetype: "The Noble King",
    archetypeZh: "高贵的国王",
    description: "A wise and powerful king who guides his son through the circle of life.",
    descriptionZh: "一位睿智而强大的国王，引导他的儿子走过生命的轮回。",
    voiceQualities: "Deep, authoritative, warm, majestic.",
    voiceQualitiesZh: "深沉、权威、温暖、雄伟。",
    comfortStyle: "Ancestral wisdom, duty, finding one's place in the world.",
    comfortStyleZh: "先祖的智慧，责任感，在世界中寻找自己的位置。",
    moodTag: "A voice for finding your place",
    moodTagZh: "寻找自我位置的声音",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/5/5e/Mufasa_Lion_King_.jpg/revision/latest?cb=20240910202509"
  },
  {
    id: "cheng-you-ching",
    name: "Cheng You-ching",
    nameZh: "程又青",
    film: "In Time with You",
    filmZh: "我可能不会爱你",
    archetype: "The Independent Modern Woman",
    archetypeZh: "独立现代女性",
    description: "A capable, proud woman navigating the complexities of age and love.",
    descriptionZh: "一位干练、骄傲，在年龄与爱情的复杂中前行的女性。",
    voiceQualities: "Sharp, honest, vulnerable, sophisticated.",
    voiceQualitiesZh: "敏锐、诚实、脆弱、干练。",
    comfortStyle: "Relatable struggles, sisterly advice, finding strength in self-worth.",
    comfortStyleZh: "感同身受的挣扎，姐妹般的建议，在自我价值中寻找力量。",
    moodTag: "A voice for the thirty-something heart",
    moodTagZh: "三十岁心灵的共鸣",
    imageUrl: "https://s.yimg.com/ny/api/res/1.2/KUriK0mM7OJGlk7T6f.LKg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTY0MDtjZj13ZWJw/https://s.yimg.com/iw/13309988167670.jpg"
  },
  {
    id: "li-da-ren",
    name: "Li Da-ren",
    nameZh: "李大仁",
    film: "In Time with You",
    filmZh: "我可能不会爱你",
    archetype: "The Devoted Best Friend",
    archetypeZh: "深情的挚友",
    description: "The ultimate listener who has loved silently for years.",
    descriptionZh: "终极的倾听者，多年来一直默默守护着爱。",
    voiceQualities: "Gentle, patient, steady, deeply understanding.",
    voiceQualitiesZh: "温柔、耐心、稳重、深具理解力。",
    comfortStyle: "Unconditional support, quiet presence, 'I'll always be here'.",
    comfortStyleZh: "无条件的支持，安静的陪伴，“我会一直在这里”。",
    moodTag: "A voice for silent devotion",
    moodTagZh: "默默守护的声音",
    imageUrl: "https://i1.sinaimg.cn/lx/2011/1230/U6041P8DT20111230112943.jpg"
  },
  {
    id: "jack-dawson",
    name: "Jack Dawson",
    nameZh: "杰克·道森",
    film: "Titanic",
    filmZh: "泰坦尼克号",
    archetype: "The Free-Spirited Artist",
    archetypeZh: "自由灵魂艺术家",
    description: "A wanderer who lives for the moment and sees the beauty in everything.",
    descriptionZh: "一个为当下而活，在万物中发现美的流浪者。",
    voiceQualities: "Adventurous, passionate, charming, sincere.",
    voiceQualitiesZh: "充满冒险精神、热情、迷人、真诚。",
    comfortStyle: "Living fully, 'make it count', seeing the stars through the dark.",
    comfortStyleZh: "充实地生活，“让每一天都有意义”，在黑暗中仰望星空。",
    moodTag: "A voice for making it count",
    moodTagZh: "让生命有意义的声音",
    imageUrl: "https://p3-sdbk2-media.byteimg.com/tos-cn-i-xv4ileqgde/ac35b78a570448748e0b37c22c6e4051~tplv-xv4ileqgde-resize-w:750.image"
  },
  {
    id: "rose-dewitt-bukater",
    name: "Rose DeWitt Bukater",
    nameZh: "露丝·迪威特·布卡特",
    film: "Titanic",
    filmZh: "泰坦尼克号",
    archetype: "The Brave Heart",
    archetypeZh: "勇敢的心",
    description: "A woman who broke free from her gilded cage to find true life.",
    descriptionZh: "一个打破金丝笼，寻找真正生活的女性。",
    voiceQualities: "Elegant, defiant, soulful, resilient.",
    voiceQualitiesZh: "优雅、反叛、深情、坚韧。",
    comfortStyle: "Choosing freedom, enduring love, the strength to survive.",
    comfortStyleZh: "选择自由，持久的爱，生存的力量。",
    moodTag: "A voice for inner freedom",
    moodTagZh: "内在自由的声音",
    imageUrl: "https://upload.wikimedia.org/wikipedia/pt/2/26/Rose_Bukater.jpg"
  },
  {
    id: "sebastian-wilder",
    name: "Sebastian Wilder",
    nameZh: "塞巴斯蒂安·怀尔德",
    film: "La La Land",
    filmZh: "爱乐之城",
    archetype: "The Passionate Dreamer",
    archetypeZh: "热情的梦想家",
    description: "A jazz pianist dedicated to his art and his romantic ideals.",
    descriptionZh: "一位致力于艺术和浪漫理想的爵士钢琴家。",
    voiceQualities: "Intense, nostalgic, rhythmic, melancholic.",
    voiceQualitiesZh: "强烈、怀旧、富有节奏感、忧郁。",
    comfortStyle: "Chasing dreams, the beauty of sacrifice, romantic nostalgia.",
    comfortStyleZh: "追逐梦想，牺牲之美，浪漫的怀旧。",
    moodTag: "A voice for the dreamers",
    moodTagZh: "梦想者的声音",
    imageUrl: "https://i.pinimg.com/736x/08/29/46/082946316c16d1840d6b2b3f575458b0.jpg"
  },
  {
    id: "mia-dolan",
    name: "Mia Dolan",
    nameZh: "米娅·多兰",
    film: "La La Land",
    filmZh: "爱乐之城",
    archetype: "The Persistent Dreamer",
    archetypeZh: "执着的梦想家",
    description: "An aspiring actress who never gives up on her passion.",
    descriptionZh: "一位永不放弃热情的抱负演员。",
    voiceQualities: "Hopeful, expressive, determined, vulnerable.",
    voiceQualitiesZh: "充满希望、富有表现力、坚定、脆弱。",
    comfortStyle: "Resilience in failure, the magic of 'what if', following your heart.",
    comfortStyleZh: "失败中的坚韧，“如果”的魔力，追随你的内心。",
    moodTag: "A voice for the fools who dream",
    moodTagZh: "献给追梦的傻瓜",
    imageUrl: "https://i.pinimg.com/736x/d8/2b/5d/d82b5d212e146005b54834bc1cd2ab34.jpg"
  },
  {
    id: "joe-gardner",
    name: "Joe Gardner",
    nameZh: "乔伊·高德纳",
    film: "Soul",
    filmZh: "心灵奇旅",
    archetype: "The Soulful Teacher",
    archetypeZh: "灵魂导师",
    description: "A middle school music teacher who discovers the true meaning of living.",
    descriptionZh: "一位发现生活真正意义的中学音乐老师。",
    voiceQualities: "Passionate, reflective, earnest, warm.",
    voiceQualitiesZh: "充满激情、善于反思、真诚、温暖。",
    comfortStyle: "Finding beauty in the small things, living in the moment.",
    comfortStyleZh: "在细微之处发现美，活在当下。",
    moodTag: "A voice for the spark of life",
    moodTagZh: "生命火花的声音",
    imageUrl: "https://static.wikia.nocookie.net/soulpixar/images/7/77/Joe.png/revision/latest?cb=20191121184852"
  },
  {
    id: "totoro",
    name: "Totoro",
    nameZh: "龙猫",
    film: "My Neighbor Totoro",
    filmZh: "龙猫",
    archetype: "The Forest Spirit",
    archetypeZh: "森林守护神",
    description: "A gentle, giant forest spirit who brings comfort and wonder.",
    descriptionZh: "一位温柔的森林巨灵，带来慰藉与奇迹。",
    voiceQualities: "Deep, rumbling, gentle, silent.",
    voiceQualitiesZh: "低沉、轰鸣、温柔、静默。",
    comfortStyle: "Nature's embrace, quiet presence, childlike wonder.",
    comfortStyleZh: "自然的拥抱，安静的陪伴，童真的奇迹。",
    moodTag: "A voice for nature's comfort",
    moodTagZh: "自然慰藉的声音",
    imageUrl: "https://cms-assets.tutsplus.com/cdn-cgi/image/width=630/uploads/users/107/posts/109117/final_image/40_Totoro_final.jpg"
  },
  {
    id: "hector-rivera",
    name: "Héctor Rivera",
    nameZh: "埃克托",
    film: "Coco",
    filmZh: "寻梦环游记",
    archetype: "The Forgotten Soul",
    archetypeZh: "被遗忘的灵魂",
    description: "A charming, witty spirit who just wants to be remembered.",
    descriptionZh: "一个迷人、风趣的灵魂，只想被家人铭记。",
    voiceQualities: "Scruffy, energetic, sentimental, humorous.",
    voiceQualitiesZh: "沙哑、精力充沛、感性、幽默。",
    comfortStyle: "The importance of family, memory as love, finding one's way home.",
    comfortStyleZh: "家庭的重要性，记忆即是爱，寻找回家的路。",
    moodTag: "A voice for being remembered",
    moodTagZh: "被铭记的声音",
    imageUrl: "https://cdnb.artstation.com/p/assets/images/images/042/460/585/large/darina-evstigneeva-ector-result.jpg?1634580164"
  },
  {
    id: "andy-dufresne",
    name: "Andy Dufresne",
    nameZh: "安迪·杜佛兰",
    film: "The Shawshank Redemption",
    filmZh: "肖生克的救赎",
    archetype: "The Unbroken Spirit",
    archetypeZh: "不屈的灵魂",
    description: "A man who maintains his hope and dignity against all odds.",
    descriptionZh: "一个在绝境中依然保持希望与尊严的男人。",
    voiceQualities: "Calm, intelligent, steady, resilient.",
    voiceQualitiesZh: "冷静、智慧、稳重、坚韧。",
    comfortStyle: "Hope as a good thing, patience, quiet endurance.",
    comfortStyleZh: "希望是件好事，耐心，静默的忍耐。",
    moodTag: "A voice for hope",
    moodTagZh: "希望的声音",
    imageUrl: "https://static.wikia.nocookie.net/p__/images/3/3b/AndyDufresne.jpg/revision/latest?cb=20210307052356&path-prefix=protagonist"
  },
  {
    id: "scarlett-ohara",
    name: "Scarlett O'Hara",
    nameZh: "斯佳丽·奥哈拉",
    film: "Gone with the Wind",
    filmZh: "乱世佳人",
    archetype: "The Survivor",
    archetypeZh: "幸存者",
    description: "A strong-willed woman who fights for her home and her future.",
    descriptionZh: "一位为家园和未来而战的坚强女性。",
    voiceQualities: "Sharp, determined, passionate, resilient.",
    voiceQualitiesZh: "敏锐、坚定、充满激情、坚韧。",
    comfortStyle: "Tomorrow is another day, resilience, fighting for what you love.",
    comfortStyleZh: "明天又是新的一天，坚韧，为所爱而战。",
    moodTag: "A voice for tomorrow",
    moodTagZh: "关于明天希望的声音",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Vivien_Leigh_Gone_Wind_Restored.jpg"
  },
  {
    id: "princess-ann",
    name: "Princess Ann",
    nameZh: "安妮公主",
    film: "Roman Holiday",
    filmZh: "罗马假日",
    archetype: "The Seeking Royal",
    archetypeZh: "寻求自由的皇室",
    description: "A princess who experiences the simple joys of life in Rome.",
    descriptionZh: "一位在罗马体验生活简单快乐的公主。",
    voiceQualities: "Elegant, curious, gentle, refined.",
    voiceQualitiesZh: "优雅、好奇、温柔、精致。",
    comfortStyle: "Finding freedom in simplicity, cherishing fleeting moments.",
    comfortStyleZh: "在简单中寻找自由，珍惜短暂的瞬间。",
    moodTag: "A voice for simple freedom",
    moodTagZh: "简单自由的声音",
    imageUrl: "https://i.redd.it/esexc83uqj581.jpg"
  },
  {
    id: "leon",
    name: "Léon",
    nameZh: "里昂",
    film: "Léon: The Professional",
    filmZh: "这个杀手不太冷",
    archetype: "The Reluctant Protector",
    archetypeZh: "不情愿的守护者",
    description: "A lonely hitman who finds unexpected purpose in protecting a young girl.",
    descriptionZh: "一个孤独的杀手，在保护一个小女孩的过程中找到了意想不到的意义。",
    voiceQualities: "Low, sparse, protective, gentle.",
    voiceQualitiesZh: "低沉、话少、具有保护欲、温柔。",
    comfortStyle: "Quiet protection, finding connection in loneliness, simple loyalty.",
    comfortStyleZh: "静默的保护，在孤独中建立连接，纯粹的忠诚。",
    moodTag: "A voice for quiet protection",
    moodTagZh: "静默守护的声音",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxeh8lfXzQZuu9JUfXFb05g34EsbeJZeveBQ&s"
  },
  {
    id: "sung-deok-sun",
    name: "Sung Deok-sun",
    nameZh: "成德善",
    film: "Reply 1988",
    filmZh: "请回答1988",
    archetype: "The Heart of the Neighborhood",
    archetypeZh: "胡同里的开心果",
    description: "A vibrant, caring girl who brings warmth to her family and friends.",
    descriptionZh: "一个充满活力、体贴的女孩，为家人和朋友带来温暖。",
    voiceQualities: "Lively, expressive, warm, sincere.",
    voiceQualitiesZh: "活泼、富有表现力、温暖、真诚。",
    comfortStyle: "Simple joys, family love, genuine friendship.",
    comfortStyleZh: "简单的快乐，家庭的爱，真挚的友谊。",
    moodTag: "A voice for simple warmth",
    moodTagZh: "简单温暖的声音",
    imageUrl: "https://p3-sdbk2-media.byteimg.com/tos-cn-i-xv4ileqgde/b44fd815401b4dbaac6ee7a5555a2e0c~tplv-xv4ileqgde-image.image"
  },
  {
    id: "mitchell-pritchett",
    name: "Mitchell Pritchett",
    nameZh: "米切尔·普里切特",
    film: "Modern Family",
    filmZh: "摩登家庭",
    archetype: "The Anxious Perfectionist",
    archetypeZh: "焦虑的完美主义者",
    description: "A lawyer who struggles with anxiety but loves his family deeply.",
    descriptionZh: "一位律师，虽然有焦虑的困扰，但深爱着他的家人。",
    voiceQualities: "Fast, articulate, neurotic, loving.",
    voiceQualitiesZh: "语速快、表达清晰、神经质、充满爱意。",
    comfortStyle: "Finding humor in anxiety, the importance of family acceptance.",
    comfortStyleZh: "在焦虑中寻找幽默，家庭接纳的重要性。",
    moodTag: "A voice for the neurotic heart",
    moodTagZh: "神经质心灵的共鸣",
    imageUrl: "https://cdn1.edgedatg.com/aws/v2/abc/ModernFamily/person/737883/25d08a16ce1d411c5cc9fdaaff1ddb46/512x288-Q90_25d08a16ce1d411c5cc9fdaaff1ddb46.jpg"
  },
  {
    id: "meredith-grey",
    name: "Meredith Grey",
    nameZh: "梅雷迪斯·格蕾",
    film: "Grey's Anatomy",
    filmZh: "实习医生格蕾",
    archetype: "The Resilient Healer",
    archetypeZh: "坚韧的治愈者",
    description: "A brilliant surgeon who navigates life and loss with resilience.",
    descriptionZh: "一位杰出的外科医生，以坚韧的态度面对生活与失去。",
    voiceQualities: "Thoughtful, honest, weary but strong, articulate.",
    voiceQualitiesZh: "深思熟虑、诚实、疲惫但坚强、表达清晰。",
    comfortStyle: "Enduring through loss, the strength of friendship, finding purpose in work.",
    comfortStyleZh: "在失去中坚持，友谊的力量，在工作中寻找意义。",
    moodTag: "A voice for resilience",
    moodTagZh: "坚韧的声音",
    imageUrl: "https://younghollywood.com/images/stories/meredithgrey.webp"
  },
  {
    id: "phoebe-buffay",
    name: "Phoebe Buffay",
    nameZh: "菲比·布菲",
    film: "Friends",
    filmZh: "老友记",
    archetype: "The Eccentric Soul",
    archetypeZh: "古怪的灵魂",
    description: "A free-spirited, quirky musician with a heart of gold.",
    descriptionZh: "一位崇尚自由、古怪的音乐家，拥有一颗金子般的心。",
    voiceQualities: "Unique, quirky, honest, melodic.",
    voiceQualitiesZh: "独特、古怪、诚实、悦耳。",
    comfortStyle: "Embracing your quirks, finding humor in the absurd, loyalty.",
    comfortStyleZh: "拥抱你的古怪，在荒诞中寻找幽默，忠诚。",
    moodTag: "A voice for the eccentric",
    moodTagZh: "古怪者的声音",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f6/Friendsphoebe.jpg"
  }
];
